insert into produtos (codigo, nome, quantidade, preco) values ('1', 'Empada de Frango com Catupiry', 47, 6.5) on conflict (codigo) do nothing;
insert into produtos (codigo, nome, quantidade, preco) values ('2', 'Empada de Palmito', 26, 6.5) on conflict (codigo) do nothing;
insert into produtos (codigo, nome, quantidade, preco) values ('3', 'Empada de Carne Seca', 24, 7) on conflict (codigo) do nothing;
insert into produtos (codigo, nome, quantidade, preco) values ('4', 'Empada Doce (Leite Condensado)', 20, 6) on conflict (codigo) do nothing;
insert into produtos (codigo, nome, quantidade, preco) values ('10', 'Coxinha Tradicional de Frango', 60, 5.5) on conflict (codigo) do nothing;
insert into produtos (codigo, nome, quantidade, preco) values ('11', 'Coxinha de Frango com Catupiry', 45, 6.5) on conflict (codigo) do nothing;
insert into produtos (codigo, nome, quantidade, preco) values ('20', 'Enroladinho de Salsicha', 40, 5) on conflict (codigo) do nothing;
insert into produtos (codigo, nome, quantidade, preco) values ('21', 'Enroladinho de Presunto e Queijo', 55, 5.5) on conflict (codigo) do nothing;
insert into produtos (codigo, nome, quantidade, preco) values ('30', 'Hamburg├úo Assado', 35, 8) on conflict (codigo) do nothing;
insert into produtos (codigo, nome, quantidade, preco) values ('40', 'Pastel Assado de Frango', 30, 6) on conflict (codigo) do nothing;
insert into produtos (codigo, nome, quantidade, preco) values ('41', 'Pastel Assado de Carne', 30, 6) on conflict (codigo) do nothing;
insert into produtos (codigo, nome, quantidade, preco) values ('50', 'Kibe Frito Tradicional', 40, 5.5) on conflict (codigo) do nothing;
insert into produtos (codigo, nome, quantidade, preco) values ('51', 'Kibe Recheado com Queijo', 35, 6.5) on conflict (codigo) do nothing;
insert into produtos (codigo, nome, quantidade, preco) values ('60', 'Esfiha de Carne', 50, 5) on conflict (codigo) do nothing;
insert into produtos (codigo, nome, quantidade, preco) values ('61', 'Esfiha de Frango', 45, 5) on conflict (codigo) do nothing;
insert into produtos (codigo, nome, quantidade, preco) values ('70', 'P├úo de Queijo Tradicional', 80, 3.5) on conflict (codigo) do nothing;
insert into produtos (codigo, nome, quantidade, preco) values ('71', 'P├úo de Queijo Recheado (Frango)', 4, 5.5) on conflict (codigo) do nothing;
insert into produtos (codigo, nome, quantidade, preco) values ('100', 'Refrigerante Coca-Cola Lata 350ml', 120, 5) on conflict (codigo) do nothing;
insert into produtos (codigo, nome, quantidade, preco) values ('101', 'Refrigerante Guaran├í Antarctica Lata 350ml', 100, 4.5) on conflict (codigo) do nothing;
insert into produtos (codigo, nome, quantidade, preco) values ('102', 'Suco Natural de Laranja 400ml', 20, 8) on conflict (codigo) do nothing;
insert into produtos (codigo, nome, quantidade, preco) values ('103', '├ügua Mineral Sem G├ís 500ml', 60, 3) on conflict (codigo) do nothing;
insert into produtos (codigo, nome, quantidade, preco) values ('7894900011517', 'Coca-Cola Lata (Para testar o Leitor de C├│d. Barras)', 50, 5) on conflict (codigo) do nothing;
insert into movimentacoes (id, data, tipo, total, itens) values (1791052969714, '2026-10-03T18:42:49.714Z', 'saida', 33, '[{"codigo":"1","nome":"Empada de Frango com Catupiry","quantidade":48,"preco":6.5,"quantidadeVendida":1},{"codigo":"2","nome":"Empada de Palmito","quantidade":29,"preco":6.5,"quantidadeVendida":3},{"codigo":"3","nome":"Empada de Carne Seca","quantidade":25,"preco":7,"quantidadeVendida":1}]'::jsonb) on conflict (id) do nothing;
insert into movimentacoes (id, data, tipo, total, itens) values (1790995098595, '2026-10-03T02:38:18.595Z', 'saida', 19.5, '[{"codigo":"2","nome":"Empada de Palmito","quantidade":30,"preco":6.5,"quantidadeVendida":1},{"codigo":"1","nome":"Empada de Frango com Catupiry","quantidade":50,"preco":6.5,"quantidadeVendida":2}]'::jsonb) on conflict (id) do nothing;
insert into movimentacoes (id, data, tipo, total, itens) values (1696150000000, '2026-10-01T10:30:00.000Z', 'saida', 52.5, '[{"codigo":"10","nome":"Coxinha Tradicional de Frango","quantidadeVendida":5,"preco":5.5},{"codigo":"100","nome":"Refrigerante Coca-Cola Lata 350ml","quantidadeVendida":5,"preco":5}]'::jsonb) on conflict (id) do nothing;
insert into movimentacoes (id, data, tipo, total, itens) values (1696160000000, '2026-10-01T13:45:00.000Z', 'saida', 72, '[{"codigo":"1","nome":"Empada de Frango com Catupiry","quantidadeVendida":8,"preco":6.5},{"codigo":"20","nome":"Enroladinho de Salsicha","quantidadeVendida":4,"preco":5}]'::jsonb) on conflict (id) do nothing;
insert into movimentacoes (id, data, tipo, total, itens) values (1696170000000, '2026-10-01T17:20:00.000Z', 'saida', 130, '[{"codigo":"5","nome":"Mini Empada (Cento - Encomenda)","quantidadeVendida":2,"preco":65}]'::jsonb) on conflict (id) do nothing;
insert into movimentacoes (id, data, tipo, total, itens) values (1696230000000, '2026-10-02T09:15:00.000Z', 'saida', 90, '[{"codigo":"30","nome":"Hamburg├úo Assado","quantidadeVendida":6,"preco":8},{"codigo":"70","nome":"P├úo de Queijo Tradicional","quantidadeVendida":12,"preco":3.5}]'::jsonb) on conflict (id) do nothing;
insert into movimentacoes (id, data, tipo, total, itens) values (1696240000000, '2026-10-02T12:30:00.000Z', 'saida', 101, '[{"codigo":"11","nome":"Coxinha de Frango com Catupiry","quantidadeVendida":10,"preco":6.5},{"codigo":"101","nome":"Refrigerante Guaran├í Antarctica Lata 350ml","quantidadeVendida":8,"preco":4.5}]'::jsonb) on conflict (id) do nothing;
